apiVersion: v2
icon: https://example.com/path/to/your-icon.png
name: ainon-helm
description: Umbrella chart for the AINON platform
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: app-configs
    version: 0.1.0
    condition: appConfigs.enabled
  - name: admin-app
    version: 0.1.0
    condition: adminApp.enabled
  - name: celery-beat
    version: 0.1.0
    condition: celeryBeat.enabled
  - name: celery-worker
    version: 0.1.0
    condition: celeryWorker.enabled
  - name: celery-worker-heavy
    version: 0.1.0
    condition: celeryWorkerHeavy.enabled    
  - name: clamav
    version: 0.1.0
    condition: clamav.enabled
  - name: django-web-app
    version: 0.1.0
    condition: djangoWebApp.enabled
  - name: proxy
    version: 0.1.0
    condition: proxy.enabled    
  - name: redis
    version: 0.1.0
    condition: redis.enabled
  - name: user-app
    version: 0.1.0
    condition: userApp.enabled
